// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StaticPercentageImport } from './routes/static-percentage'
import { Route as StaticLoopPercentageImport } from './routes/static-loop-percentage'
import { Route as StaticLoopImport } from './routes/static-loop'
import { Route as PercentageSkeletonImport } from './routes/percentage-skeleton'
import { Route as LoopSkeletonImport } from './routes/loop-skeleton'
import { Route as LoopPercentageSkeletonImport } from './routes/loop-percentage-skeleton'
import { Route as LoopPercentageImport } from './routes/loop-percentage'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StaticPercentageRoute = StaticPercentageImport.update({
  path: '/static-percentage',
  getParentRoute: () => rootRoute,
} as any)

const StaticLoopPercentageRoute = StaticLoopPercentageImport.update({
  path: '/static-loop-percentage',
  getParentRoute: () => rootRoute,
} as any)

const StaticLoopRoute = StaticLoopImport.update({
  path: '/static-loop',
  getParentRoute: () => rootRoute,
} as any)

const PercentageSkeletonRoute = PercentageSkeletonImport.update({
  path: '/percentage-skeleton',
  getParentRoute: () => rootRoute,
} as any)

const LoopSkeletonRoute = LoopSkeletonImport.update({
  path: '/loop-skeleton',
  getParentRoute: () => rootRoute,
} as any)

const LoopPercentageSkeletonRoute = LoopPercentageSkeletonImport.update({
  path: '/loop-percentage-skeleton',
  getParentRoute: () => rootRoute,
} as any)

const LoopPercentageRoute = LoopPercentageImport.update({
  path: '/loop-percentage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/loop-percentage': {
      preLoaderRoute: typeof LoopPercentageImport
      parentRoute: typeof rootRoute
    }
    '/loop-percentage-skeleton': {
      preLoaderRoute: typeof LoopPercentageSkeletonImport
      parentRoute: typeof rootRoute
    }
    '/loop-skeleton': {
      preLoaderRoute: typeof LoopSkeletonImport
      parentRoute: typeof rootRoute
    }
    '/percentage-skeleton': {
      preLoaderRoute: typeof PercentageSkeletonImport
      parentRoute: typeof rootRoute
    }
    '/static-loop': {
      preLoaderRoute: typeof StaticLoopImport
      parentRoute: typeof rootRoute
    }
    '/static-loop-percentage': {
      preLoaderRoute: typeof StaticLoopPercentageImport
      parentRoute: typeof rootRoute
    }
    '/static-percentage': {
      preLoaderRoute: typeof StaticPercentageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoopPercentageRoute,
  LoopPercentageSkeletonRoute,
  LoopSkeletonRoute,
  PercentageSkeletonRoute,
  StaticLoopRoute,
  StaticLoopPercentageRoute,
  StaticPercentageRoute,
])
